#!/bin/bash

if [[ $# == 1 && ("$1" == "ro" || "$1" == "rw") ]] ; then
    sudo mount.cifs //192.168.1.1/Heaven /home/mimly/Heaven -o "$1",uid=1000,gid=1000,nounix,dir_mode=00770,file_mode=00660,vers=1.0,credentials=/home/mimly/credentialsToHeaven ;
else
    echo "USAGE: mount-heaven ro|rw" ;
fi
