#!/bin/bash

if [[ $# == 1 && ("$1" == "ro" || "$1" == "rw") ]] ; then
    sudo mount.cifs //192.168.1.1/CloudInHeaven /home/mimly/CloudInHeaven -o "$1",vers=1.0,credentials=/home/mimly/credentialsToCloud
else
    echo "USAGE: mount-cloud ro|rw" ;
fi
